# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sf306/phd_codebase/FPL2014/FFF/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/hls_prj/F3_VivadoHLS_core/impl/vhdl/project.srcs/sources_1/ip/vivado_activity_thread_ap_fmul_1_max_dsp/vivado_activity_thread_ap_fmul_1_max_dsp.xci
# IP: The module: 'vivado_activity_thread_ap_fmul_1_max_dsp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sf306/phd_codebase/FPL2014/FFF/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/hls_prj/F3_VivadoHLS_core/impl/vhdl/project.srcs/sources_1/ip/vivado_activity_thread_ap_fmul_1_max_dsp/vivado_activity_thread_ap_fmul_1_max_dsp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vivado_activity_thread_ap_fmul_1_max_dsp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/sf306/phd_codebase/FPL2014/FFF/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/hls_prj/F3_VivadoHLS_core/impl/vhdl/project.srcs/sources_1/ip/vivado_activity_thread_ap_fmul_1_max_dsp/vivado_activity_thread_ap_fmul_1_max_dsp.xci
# IP: The module: 'vivado_activity_thread_ap_fmul_1_max_dsp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sf306/phd_codebase/FPL2014/FFF/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/hls_prj/F3_VivadoHLS_core/impl/vhdl/project.srcs/sources_1/ip/vivado_activity_thread_ap_fmul_1_max_dsp/vivado_activity_thread_ap_fmul_1_max_dsp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vivado_activity_thread_ap_fmul_1_max_dsp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
