lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/vivado_core.c" location "vivado_activity_thread/PATH_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/vivado_core.c" location "vivado_activity_thread/PATHSET_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/asian_option.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/asian_option.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/digital_double_barrier_option.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/digital_double_barrier_option.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/double_barrier_option.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/double_barrier_option.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/barrier_option.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/barrier_option.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/european_option.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/european_option.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/option.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/option.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/heston_underlying.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/heston_underlying.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/black_scholes_underlying.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/black_scholes_underlying.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/gauss.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/gauss.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/underlying.c" location "vivado_activity_thread/PATH_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "/mnt/cas_nfs/gi11/workspace/ForwardFinancialFramework/Platforms/VivadoFPGA/vivadohls_code/srcs/underlying.c" location "vivado_activity_thread/PATHSET_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'vivado_activity_thread' does not exist in any synthesis source file."}
