# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_system/zynq_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system || ORIG_REF_NAME==zynq_system}]

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_0_0/zynq_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0}]

# IP: bd/zynq_system/ip/zynq_system_vivado_activity_thread_0_0_0/zynq_system_vivado_activity_thread_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_vivado_activity_thread_0_0 || ORIG_REF_NAME==zynq_system_vivado_activity_thread_0_0}]

# IP: bd/zynq_system/ip/zynq_system_axi_mem_intercon_0/zynq_system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_0}]

# IP: bd/zynq_system/ip/zynq_system_xbar_0_1/zynq_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_xbar_0 || ORIG_REF_NAME==zynq_system_xbar_0}]

# IP: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_50M_0_1/zynq_system_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_50M_0}]

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_axi_periph_1/zynq_system_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==zynq_system_processing_system7_0_axi_periph_1}]

# IP: bd/zynq_system/ip/zynq_system_xbar_1_1/zynq_system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_xbar_1 || ORIG_REF_NAME==zynq_system_xbar_1}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_3_1/zynq_system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_3 || ORIG_REF_NAME==zynq_system_auto_pc_3}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_4_0/zynq_system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_4 || ORIG_REF_NAME==zynq_system_auto_pc_4}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_9_1/zynq_system_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_9 || ORIG_REF_NAME==zynq_system_auto_pc_9}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_10_1/zynq_system_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_10 || ORIG_REF_NAME==zynq_system_auto_pc_10}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_11_0/zynq_system_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_11 || ORIG_REF_NAME==zynq_system_auto_pc_11}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_40/zynq_system_auto_pc_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_40 || ORIG_REF_NAME==zynq_system_auto_pc_40}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_44/zynq_system_auto_pc_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_44 || ORIG_REF_NAME==zynq_system_auto_pc_44}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_45/zynq_system_auto_pc_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_45 || ORIG_REF_NAME==zynq_system_auto_pc_45}]

# XDC: bd/zynq_system/ip/zynq_system_processing_system7_0_0_0/zynq_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_system/ip/zynq_system_vivado_activity_thread_0_0_0/constraints/vivado_activity_thread_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_50M_0_1/zynq_system_rst_processing_system7_0_50M_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_50M_0_1/zynq_system_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_50M_0_1/zynq_system_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_system/ip/zynq_system_auto_pc_4_0/zynq_system_auto_pc_4_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_auto_pc_44/zynq_system_auto_pc_44_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_auto_pc_45/zynq_system_auto_pc_45_ooc.xdc

# XDC: bd/zynq_system/zynq_system_ooc.xdc
