// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module vivado_activity_thread_top (
s_axi_CORE_IO_AWADDR,
s_axi_CORE_IO_AWVALID,
s_axi_CORE_IO_AWREADY,
s_axi_CORE_IO_WDATA,
s_axi_CORE_IO_WSTRB,
s_axi_CORE_IO_WVALID,
s_axi_CORE_IO_WREADY,
s_axi_CORE_IO_BRESP,
s_axi_CORE_IO_BVALID,
s_axi_CORE_IO_BREADY,
s_axi_CORE_IO_ARADDR,
s_axi_CORE_IO_ARVALID,
s_axi_CORE_IO_ARREADY,
s_axi_CORE_IO_RDATA,
s_axi_CORE_IO_RRESP,
s_axi_CORE_IO_RVALID,
s_axi_CORE_IO_RREADY,
interrupt,
aresetn,
aclk
);

parameter C_S_AXI_CORE_IO_ADDR_WIDTH = 7;
parameter C_S_AXI_CORE_IO_DATA_WIDTH = 32;
parameter RESET_ACTIVE_LOW = 1;

input [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_AWADDR ;
input s_axi_CORE_IO_AWVALID ;
output s_axi_CORE_IO_AWREADY ;
input [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_WDATA ;
input [C_S_AXI_CORE_IO_DATA_WIDTH/8 - 1:0] s_axi_CORE_IO_WSTRB ;
input s_axi_CORE_IO_WVALID ;
output s_axi_CORE_IO_WREADY ;
output [2 - 1:0] s_axi_CORE_IO_BRESP ;
output s_axi_CORE_IO_BVALID ;
input s_axi_CORE_IO_BREADY ;
input [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_ARADDR ;
input s_axi_CORE_IO_ARVALID ;
output s_axi_CORE_IO_ARREADY ;
output [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_RDATA ;
output [2 - 1:0] s_axi_CORE_IO_RRESP ;
output s_axi_CORE_IO_RVALID ;
input s_axi_CORE_IO_RREADY ;
output interrupt ;

input aresetn ;

input aclk ;


wire [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_AWADDR;
wire s_axi_CORE_IO_AWVALID;
wire s_axi_CORE_IO_AWREADY;
wire [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_WDATA;
wire [C_S_AXI_CORE_IO_DATA_WIDTH/8 - 1:0] s_axi_CORE_IO_WSTRB;
wire s_axi_CORE_IO_WVALID;
wire s_axi_CORE_IO_WREADY;
wire [2 - 1:0] s_axi_CORE_IO_BRESP;
wire s_axi_CORE_IO_BVALID;
wire s_axi_CORE_IO_BREADY;
wire [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_ARADDR;
wire s_axi_CORE_IO_ARVALID;
wire s_axi_CORE_IO_ARREADY;
wire [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_RDATA;
wire [2 - 1:0] s_axi_CORE_IO_RRESP;
wire s_axi_CORE_IO_RVALID;
wire s_axi_CORE_IO_RREADY;
wire interrupt;

wire aresetn;


wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_thread_paths;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_path_points;
wire sig_vivado_activity_thread_thread_arg_path_points_ap_vld;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_thread_result;
wire sig_vivado_activity_thread_thread_arg_thread_result_ap_vld;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_thread_result_sqrd;
wire sig_vivado_activity_thread_thread_arg_thread_result_sqrd_ap_vld;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_u_a_0_rfir;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_u_a_0_current_price;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_o_a_0_strike_price;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_o_a_0_time_period;
wire [32 - 1:0] sig_vivado_activity_thread_thread_arg_o_a_0_call;
wire sig_vivado_activity_thread_ap_start;
wire sig_vivado_activity_thread_ap_ready;
wire sig_vivado_activity_thread_ap_done;
wire sig_vivado_activity_thread_ap_idle;

wire sig_vivado_activity_thread_ap_rst;



vivado_activity_thread vivado_activity_thread_U(
    .thread_arg_thread_paths(sig_vivado_activity_thread_thread_arg_thread_paths),
    .thread_arg_path_points(sig_vivado_activity_thread_thread_arg_path_points),
    .thread_arg_path_points_ap_vld(sig_vivado_activity_thread_thread_arg_path_points_ap_vld),
    .thread_arg_thread_result(sig_vivado_activity_thread_thread_arg_thread_result),
    .thread_arg_thread_result_ap_vld(sig_vivado_activity_thread_thread_arg_thread_result_ap_vld),
    .thread_arg_thread_result_sqrd(sig_vivado_activity_thread_thread_arg_thread_result_sqrd),
    .thread_arg_thread_result_sqrd_ap_vld(sig_vivado_activity_thread_thread_arg_thread_result_sqrd_ap_vld),
    .thread_arg_u_a_0_rfir(sig_vivado_activity_thread_thread_arg_u_a_0_rfir),
    .thread_arg_u_a_0_current_price(sig_vivado_activity_thread_thread_arg_u_a_0_current_price),
    .thread_arg_o_a_0_strike_price(sig_vivado_activity_thread_thread_arg_o_a_0_strike_price),
    .thread_arg_o_a_0_time_period(sig_vivado_activity_thread_thread_arg_o_a_0_time_period),
    .thread_arg_o_a_0_call(sig_vivado_activity_thread_thread_arg_o_a_0_call),
    .ap_start(sig_vivado_activity_thread_ap_start),
    .ap_ready(sig_vivado_activity_thread_ap_ready),
    .ap_done(sig_vivado_activity_thread_ap_done),
    .ap_idle(sig_vivado_activity_thread_ap_idle),
    .ap_rst(sig_vivado_activity_thread_ap_rst),
    .ap_clk(aclk)
);

vivado_activity_thread_CORE_IO_if #(
    .C_ADDR_WIDTH(C_S_AXI_CORE_IO_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_CORE_IO_DATA_WIDTH))
vivado_activity_thread_CORE_IO_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .I_thread_arg_thread_paths(sig_vivado_activity_thread_thread_arg_thread_paths),
    .O_thread_arg_path_points(sig_vivado_activity_thread_thread_arg_path_points),
    .O_thread_arg_path_points_ap_vld(sig_vivado_activity_thread_thread_arg_path_points_ap_vld),
    .O_thread_arg_thread_result(sig_vivado_activity_thread_thread_arg_thread_result),
    .O_thread_arg_thread_result_ap_vld(sig_vivado_activity_thread_thread_arg_thread_result_ap_vld),
    .O_thread_arg_thread_result_sqrd(sig_vivado_activity_thread_thread_arg_thread_result_sqrd),
    .O_thread_arg_thread_result_sqrd_ap_vld(sig_vivado_activity_thread_thread_arg_thread_result_sqrd_ap_vld),
    .I_thread_arg_u_a_0_rfir(sig_vivado_activity_thread_thread_arg_u_a_0_rfir),
    .I_thread_arg_u_a_0_current_price(sig_vivado_activity_thread_thread_arg_u_a_0_current_price),
    .I_thread_arg_o_a_0_strike_price(sig_vivado_activity_thread_thread_arg_o_a_0_strike_price),
    .I_thread_arg_o_a_0_time_period(sig_vivado_activity_thread_thread_arg_o_a_0_time_period),
    .I_thread_arg_o_a_0_call(sig_vivado_activity_thread_thread_arg_o_a_0_call),
    .I_ap_start(sig_vivado_activity_thread_ap_start),
    .O_ap_ready(sig_vivado_activity_thread_ap_ready),
    .O_ap_done(sig_vivado_activity_thread_ap_done),
    .O_ap_idle(sig_vivado_activity_thread_ap_idle),
    .AWADDR(s_axi_CORE_IO_AWADDR),
    .AWVALID(s_axi_CORE_IO_AWVALID),
    .AWREADY(s_axi_CORE_IO_AWREADY),
    .WDATA(s_axi_CORE_IO_WDATA),
    .WSTRB(s_axi_CORE_IO_WSTRB),
    .WVALID(s_axi_CORE_IO_WVALID),
    .WREADY(s_axi_CORE_IO_WREADY),
    .BRESP(s_axi_CORE_IO_BRESP),
    .BVALID(s_axi_CORE_IO_BVALID),
    .BREADY(s_axi_CORE_IO_BREADY),
    .ARADDR(s_axi_CORE_IO_ARADDR),
    .ARVALID(s_axi_CORE_IO_ARVALID),
    .ARREADY(s_axi_CORE_IO_ARREADY),
    .RDATA(s_axi_CORE_IO_RDATA),
    .RRESP(s_axi_CORE_IO_RRESP),
    .RVALID(s_axi_CORE_IO_RVALID),
    .RREADY(s_axi_CORE_IO_RREADY),
    .interrupt(interrupt));

vivado_activity_thread_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_vivado_activity_thread_ap_rst),
    .din(aresetn));

endmodule
