// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module vivado_activity_thread_top (
s_axi_CORE_IO_AWADDR,
s_axi_CORE_IO_AWVALID,
s_axi_CORE_IO_AWREADY,
s_axi_CORE_IO_WDATA,
s_axi_CORE_IO_WSTRB,
s_axi_CORE_IO_WVALID,
s_axi_CORE_IO_WREADY,
s_axi_CORE_IO_BRESP,
s_axi_CORE_IO_BVALID,
s_axi_CORE_IO_BREADY,
s_axi_CORE_IO_ARADDR,
s_axi_CORE_IO_ARVALID,
s_axi_CORE_IO_ARREADY,
s_axi_CORE_IO_RDATA,
s_axi_CORE_IO_RRESP,
s_axi_CORE_IO_RVALID,
s_axi_CORE_IO_RREADY,
interrupt,
aresetn,
aclk
);

parameter C_S_AXI_CORE_IO_ADDR_WIDTH = 8;
parameter C_S_AXI_CORE_IO_DATA_WIDTH = 32;
parameter RESET_ACTIVE_LOW = 1;

input [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_AWADDR ;
input s_axi_CORE_IO_AWVALID ;
output s_axi_CORE_IO_AWREADY ;
input [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_WDATA ;
input [C_S_AXI_CORE_IO_DATA_WIDTH/8 - 1:0] s_axi_CORE_IO_WSTRB ;
input s_axi_CORE_IO_WVALID ;
output s_axi_CORE_IO_WREADY ;
output [2 - 1:0] s_axi_CORE_IO_BRESP ;
output s_axi_CORE_IO_BVALID ;
input s_axi_CORE_IO_BREADY ;
input [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_ARADDR ;
input s_axi_CORE_IO_ARVALID ;
output s_axi_CORE_IO_ARREADY ;
output [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_RDATA ;
output [2 - 1:0] s_axi_CORE_IO_RRESP ;
output s_axi_CORE_IO_RVALID ;
input s_axi_CORE_IO_RREADY ;
output interrupt ;

input aresetn ;

input aclk ;


wire [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_AWADDR;
wire s_axi_CORE_IO_AWVALID;
wire s_axi_CORE_IO_AWREADY;
wire [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_WDATA;
wire [C_S_AXI_CORE_IO_DATA_WIDTH/8 - 1:0] s_axi_CORE_IO_WSTRB;
wire s_axi_CORE_IO_WVALID;
wire s_axi_CORE_IO_WREADY;
wire [2 - 1:0] s_axi_CORE_IO_BRESP;
wire s_axi_CORE_IO_BVALID;
wire s_axi_CORE_IO_BREADY;
wire [C_S_AXI_CORE_IO_ADDR_WIDTH - 1:0] s_axi_CORE_IO_ARADDR;
wire s_axi_CORE_IO_ARVALID;
wire s_axi_CORE_IO_ARREADY;
wire [C_S_AXI_CORE_IO_DATA_WIDTH - 1:0] s_axi_CORE_IO_RDATA;
wire [2 - 1:0] s_axi_CORE_IO_RRESP;
wire s_axi_CORE_IO_RVALID;
wire s_axi_CORE_IO_RREADY;
wire interrupt;

wire aresetn;


wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_rfir;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_current_price;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_volatility;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_initial_volatility;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_volatility_volatility;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_rho;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_kappa;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_theta;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_0_0;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_0_1;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_1_0;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_1_1;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_second_barrier;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_barrier;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_out;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_down;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_strike_price;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_time_period;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_call;
wire [32 - 1:0] sig_vivado_activity_thread_kernel_o_a_0_points;
wire [32 - 1:0] sig_vivado_activity_thread_seed_0_s1;
wire [32 - 1:0] sig_vivado_activity_thread_seed_0_s2;
wire [32 - 1:0] sig_vivado_activity_thread_seed_0_s3;
wire [32 - 1:0] sig_vivado_activity_thread_seed_0_offset;
wire [32 - 1:0] sig_vivado_activity_thread_thread_result_0;
wire sig_vivado_activity_thread_thread_result_0_ap_vld;
wire [32 - 1:0] sig_vivado_activity_thread_thread_result_sqrd_0;
wire sig_vivado_activity_thread_thread_result_sqrd_0_ap_vld;
wire sig_vivado_activity_thread_ap_start;
wire sig_vivado_activity_thread_ap_ready;
wire sig_vivado_activity_thread_ap_done;
wire sig_vivado_activity_thread_ap_idle;

wire sig_vivado_activity_thread_ap_rst;



vivado_activity_thread vivado_activity_thread_U(
    .kernel_u_a_0_rfir(sig_vivado_activity_thread_kernel_u_a_0_rfir),
    .kernel_u_a_0_current_price(sig_vivado_activity_thread_kernel_u_a_0_current_price),
    .kernel_u_a_0_volatility(sig_vivado_activity_thread_kernel_u_a_0_volatility),
    .kernel_u_a_0_initial_volatility(sig_vivado_activity_thread_kernel_u_a_0_initial_volatility),
    .kernel_u_a_0_volatility_volatility(sig_vivado_activity_thread_kernel_u_a_0_volatility_volatility),
    .kernel_u_a_0_rho(sig_vivado_activity_thread_kernel_u_a_0_rho),
    .kernel_u_a_0_kappa(sig_vivado_activity_thread_kernel_u_a_0_kappa),
    .kernel_u_a_0_theta(sig_vivado_activity_thread_kernel_u_a_0_theta),
    .kernel_u_a_0_correlation_matrix_0_0(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_0_0),
    .kernel_u_a_0_correlation_matrix_0_1(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_0_1),
    .kernel_u_a_0_correlation_matrix_1_0(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_1_0),
    .kernel_u_a_0_correlation_matrix_1_1(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_1_1),
    .kernel_o_a_0_second_barrier(sig_vivado_activity_thread_kernel_o_a_0_second_barrier),
    .kernel_o_a_0_barrier(sig_vivado_activity_thread_kernel_o_a_0_barrier),
    .kernel_o_a_0_out(sig_vivado_activity_thread_kernel_o_a_0_out),
    .kernel_o_a_0_down(sig_vivado_activity_thread_kernel_o_a_0_down),
    .kernel_o_a_0_strike_price(sig_vivado_activity_thread_kernel_o_a_0_strike_price),
    .kernel_o_a_0_time_period(sig_vivado_activity_thread_kernel_o_a_0_time_period),
    .kernel_o_a_0_call(sig_vivado_activity_thread_kernel_o_a_0_call),
    .kernel_o_a_0_points(sig_vivado_activity_thread_kernel_o_a_0_points),
    .seed_0_s1(sig_vivado_activity_thread_seed_0_s1),
    .seed_0_s2(sig_vivado_activity_thread_seed_0_s2),
    .seed_0_s3(sig_vivado_activity_thread_seed_0_s3),
    .seed_0_offset(sig_vivado_activity_thread_seed_0_offset),
    .thread_result_0(sig_vivado_activity_thread_thread_result_0),
    .thread_result_0_ap_vld(sig_vivado_activity_thread_thread_result_0_ap_vld),
    .thread_result_sqrd_0(sig_vivado_activity_thread_thread_result_sqrd_0),
    .thread_result_sqrd_0_ap_vld(sig_vivado_activity_thread_thread_result_sqrd_0_ap_vld),
    .ap_start(sig_vivado_activity_thread_ap_start),
    .ap_ready(sig_vivado_activity_thread_ap_ready),
    .ap_done(sig_vivado_activity_thread_ap_done),
    .ap_idle(sig_vivado_activity_thread_ap_idle),
    .ap_rst(sig_vivado_activity_thread_ap_rst),
    .ap_clk(aclk)
);

vivado_activity_thread_CORE_IO_if #(
    .C_ADDR_WIDTH(C_S_AXI_CORE_IO_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_CORE_IO_DATA_WIDTH))
vivado_activity_thread_CORE_IO_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .I_kernel_u_a_0_rfir(sig_vivado_activity_thread_kernel_u_a_0_rfir),
    .I_kernel_u_a_0_current_price(sig_vivado_activity_thread_kernel_u_a_0_current_price),
    .I_kernel_u_a_0_volatility(sig_vivado_activity_thread_kernel_u_a_0_volatility),
    .I_kernel_u_a_0_initial_volatility(sig_vivado_activity_thread_kernel_u_a_0_initial_volatility),
    .I_kernel_u_a_0_volatility_volatility(sig_vivado_activity_thread_kernel_u_a_0_volatility_volatility),
    .I_kernel_u_a_0_rho(sig_vivado_activity_thread_kernel_u_a_0_rho),
    .I_kernel_u_a_0_kappa(sig_vivado_activity_thread_kernel_u_a_0_kappa),
    .I_kernel_u_a_0_theta(sig_vivado_activity_thread_kernel_u_a_0_theta),
    .I_kernel_u_a_0_correlation_matrix_0_0(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_0_0),
    .I_kernel_u_a_0_correlation_matrix_0_1(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_0_1),
    .I_kernel_u_a_0_correlation_matrix_1_0(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_1_0),
    .I_kernel_u_a_0_correlation_matrix_1_1(sig_vivado_activity_thread_kernel_u_a_0_correlation_matrix_1_1),
    .I_kernel_o_a_0_second_barrier(sig_vivado_activity_thread_kernel_o_a_0_second_barrier),
    .I_kernel_o_a_0_barrier(sig_vivado_activity_thread_kernel_o_a_0_barrier),
    .I_kernel_o_a_0_out(sig_vivado_activity_thread_kernel_o_a_0_out),
    .I_kernel_o_a_0_down(sig_vivado_activity_thread_kernel_o_a_0_down),
    .I_kernel_o_a_0_strike_price(sig_vivado_activity_thread_kernel_o_a_0_strike_price),
    .I_kernel_o_a_0_time_period(sig_vivado_activity_thread_kernel_o_a_0_time_period),
    .I_kernel_o_a_0_call(sig_vivado_activity_thread_kernel_o_a_0_call),
    .I_kernel_o_a_0_points(sig_vivado_activity_thread_kernel_o_a_0_points),
    .I_seed_0_s1(sig_vivado_activity_thread_seed_0_s1),
    .I_seed_0_s2(sig_vivado_activity_thread_seed_0_s2),
    .I_seed_0_s3(sig_vivado_activity_thread_seed_0_s3),
    .I_seed_0_offset(sig_vivado_activity_thread_seed_0_offset),
    .O_thread_result_0(sig_vivado_activity_thread_thread_result_0),
    .O_thread_result_0_ap_vld(sig_vivado_activity_thread_thread_result_0_ap_vld),
    .O_thread_result_sqrd_0(sig_vivado_activity_thread_thread_result_sqrd_0),
    .O_thread_result_sqrd_0_ap_vld(sig_vivado_activity_thread_thread_result_sqrd_0_ap_vld),
    .I_ap_start(sig_vivado_activity_thread_ap_start),
    .O_ap_ready(sig_vivado_activity_thread_ap_ready),
    .O_ap_done(sig_vivado_activity_thread_ap_done),
    .O_ap_idle(sig_vivado_activity_thread_ap_idle),
    .AWADDR(s_axi_CORE_IO_AWADDR),
    .AWVALID(s_axi_CORE_IO_AWVALID),
    .AWREADY(s_axi_CORE_IO_AWREADY),
    .WDATA(s_axi_CORE_IO_WDATA),
    .WSTRB(s_axi_CORE_IO_WSTRB),
    .WVALID(s_axi_CORE_IO_WVALID),
    .WREADY(s_axi_CORE_IO_WREADY),
    .BRESP(s_axi_CORE_IO_BRESP),
    .BVALID(s_axi_CORE_IO_BVALID),
    .BREADY(s_axi_CORE_IO_BREADY),
    .ARADDR(s_axi_CORE_IO_ARADDR),
    .ARVALID(s_axi_CORE_IO_ARVALID),
    .ARREADY(s_axi_CORE_IO_ARREADY),
    .RDATA(s_axi_CORE_IO_RDATA),
    .RRESP(s_axi_CORE_IO_RRESP),
    .RVALID(s_axi_CORE_IO_RVALID),
    .RREADY(s_axi_CORE_IO_RREADY),
    .interrupt(interrupt));

vivado_activity_thread_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_vivado_activity_thread_ap_rst),
    .din(aresetn));

endmodule
